version: "3.9"
services:
  kliker:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 122880
        hard: 122880
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    volumes:
      - ./deploy:/deploy
    ports:
      - "80:7890"